import { StyleSheet, Image, useWindowDimensions, Dimensions } from 'react-native';

export const nounGlassesUris = [
  require('../../images/glasses/glasses-deep-teal.png'),
  require('../../images/glasses/glasses-grass.png'),
  require('../../images/glasses/glasses-hip-rose.png'),
  require('../../images/glasses/glasses-square-black-eyes-red.png'),
  require('../../images/glasses/glasses-square-black-rgb.png'),
  require('../../images/glasses/glasses-square-black.png'),
  require('../../images/glasses/glasses-square-blue-med-saturated.png'),
  require('../../images/glasses/glasses-square-blue.png'),
  require('../../images/glasses/glasses-square-frog-green.png'),
  require('../../images/glasses/glasses-square-fullblack.png'),
  require('../../images/glasses/glasses-square-green-blue-multi.png'),
  require('../../images/glasses/glasses-square-grey-light.png'),
  require('../../images/glasses/glasses-square-guava.png'),
  require('../../images/glasses/glasses-square-honey.png'),
  require('../../images/glasses/glasses-square-magenta.png'),
  require('../../images/glasses/glasses-square-orange.png'),
  require('../../images/glasses/glasses-square-pink-purple-multi.png'),
  require('../../images/glasses/glasses-square-red.png'),
  require('../../images/glasses/glasses-square-smoke.png'),
  require('../../images/glasses/glasses-square-teal.png'),
  require('../../images/glasses/glasses-square-watermelon.png'),
  require('../../images/glasses/glasses-square-yellow-orange-multi.png'),
  require('../../images/glasses/glasses-square-yellow-saturated.png'),
];

export const nounHeadUris = [
  '../images/heads/head-aardvark.png',
  '../images/heads/head-abstract.png',
  '../images/heads/head-ape.png',
  '../images/heads/head-bag.png',
  '../images/heads/head-bagpipe.png',
  '../images/heads/head-banana.png',
  '../images/heads/head-bank.png',
  '../images/heads/head-baseball-gameball.png',
  '../images/heads/head-basketball.png',
  '../images/heads/head-bat.png',
  '../images/heads/head-bear.png',
  '../images/heads/head-beer.png',
  '../images/heads/head-beet.png',
  '../images/heads/head-bell.png',
  '../images/heads/head-bigfoot-yeti.png',
  '../images/heads/head-bigfoot.png',
  '../images/heads/head-blackhole.png',
  '../images/heads/head-blueberry.png',
  '../images/heads/head-bomb.png',
  '../images/heads/head-bonsai.png',
  '../images/heads/head0boombox.png',
  '../images/heads/head-boot.png',
  '../images/heads/head-bonsai.png',
];
